In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [4]:
first_value = int(input("Enter value one "))
second_value = int(input("Enter value two"))
np.zeros((first_value,second_value), dtype=int)

Enter value one 3
Enter value two3


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.random.seed(2) #to make the random display same value always
val = np.random.randint(10, size=5)
val

array([8, 8, 6, 2, 8])

# Assignment 1
1) Generate a np array of vector of length 50 and two dimensional of shape 4x5 uniformly distibuted between 0 and 1
2) Split the two dimension array into three arrays taking the first two rows, follow by the next two rows and put the remaining in another variable
3) split the vector into three arrays by taking the first 15, follow by the next 20 amd the remaining into another variable
4) Create a 4x5 array manually (b) using random generated value between 0 and 1 (c) using array of ones

In [2]:
import pandas as pd
births = pd.read_csv('C:\\Users\HP\\Documents\\NUMPY\\new_births.csv')

In [3]:
birth_2002 = births[births['year'] == 2002]
birth_2002.head()

year gender  births
15379  2002      F  161477
15380  2002      M  169612
15381  2002      F  148745
15382  2002      M  155627
15383  2002      F  162351

In [13]:
birth_year = np.array(birth_2002['year'])
birth_gender = np.array(birth_2002['gender'])
birth_no = np.array(birth_2002['births'])
birth_no

array([161477, 169612, 148745, 155627, 162351, 169543, 158674, 166175,
       165530, 173925, 159792, 168261, 175085, 183135, 175501, 184444,
       170451, 178945, 169482, 176842, 155849, 163200, 163582, 171148],
      dtype=int64)

In [6]:
total_birth = np.sum(birth_no)
print(f"The total number of births in the year 2002 is {total_birth}")

The total number of births in the year 2002 is 4027376


In [11]:
females = birth_2002[birth_2002['gender'] == "F"]
female_births = np.array(females['births'])
total_female_births = np.sum(female_births)
print(f"The total number of female children given birth to in the year 2002 is {total_female_births}")

The total number of female children given birth to in the year 2002 is 1966519


In [12]:
males = birth_2002[birth_2002['gender'] == "M"]
male_births = np.array(males['births'])
total_male_births = np.sum(male_births)
print(f"The total number of male children given birth to in the year 2002 is {total_male_births}")

The total number of male children given birth to in the year 2002 is 2060857


In [16]:
print(f"In 2002, the mean of children births is {np.mean(birth_no)}, and the median is {np.median(birth_no)}")

In 2002, the mean of children births is 167807.33333333334, and the median is 168871.5


In [20]:
max_birth = np.max(birth_no)
min_birth = np.min(birth_no)
print(f"The maximum births in 2002 is {max_birth} and the minimum births is {min_birth}")

The maximum births in 2002 is 184444 and the minimum births is 148745


In [26]:
max_birth_info = birth_2002[birth_2002['births'] == max_birth]
min_birth_info = birth_2002[birth_2002['births'] == min_birth]
print("The Male gender has the highest number of births while the Female gender has the lowest number of births in the year 2002")

The Male gender has the highest number of births while the Female gender has the lowest number of births in the year 2002


In [ ]:
import numpy as np

# Task 1
vector = np.linspace(0, 1, 50)
two_dim_array = np.linspace(0, 1, (4, 5))

# Task 2
# array1 = two_dim_array[:2, :]
# array2 = two_dim_array[2:4, :]
# remaining_array = two_dim_array[4:, :]

#Alternative to task 2
first, second, third = np.vsplit(two_dim_array, [2,4])

# Task 3
# array1_vector = vector[:15]
# array2_vector = vector[15:35]
# remaining_vector = vector[35:]

#Alternative to task 3
arr1, arr2, arr3 = np.split(vector, (15, 35))

# Task 4
array_b = np.random.random((4, 5))
array_c = np.ones((4, 5))


# Assignment 2

In [1]:
import numpy as np
import pandas as pd

In [2]:
anime_characters = pd.Series(["asta", "luffy", "escanor", "kaneki", "altair", "esdeath", "mikasa", "deku", "marin", "kirito"], index=['Black Clover', 'One Piece', 'Seven Deadly Sins', 'Tokyo Ghoul', 'Re: Creators', 'Akame Ga Kill', 'AOT', 'My Hero Academia', 'My Dressup Darling', 'Sword Art Online'])
anime_characters

Black Clover             asta
One Piece               luffy
Seven Deadly Sins     escanor
Tokyo Ghoul            kaneki
Re: Creators           altair
Akame Ga Kill         esdeath
AOT                    mikasa
My Hero Academia         deku
My Dressup Darling      marin
Sword Art Online       kirito
dtype: object

In [3]:
states = pd.Series({"Abia": "Umaya", "Adamawa":"Yola", "Akwa-Ibom":"Uyo", "Anambra":"Awka", "Bauchi":"Bauchi", "Bayelsa":"Yenagoa", "Benue":"Makurdi", "Borno":"Maiduguri", "Cross River":"Calabar", "Delta":"Asaba", "Ebonyi":"Abakaliki"})
states

Abia               Umaya
Adamawa             Yola
Akwa-Ibom            Uyo
Anambra             Awka
Bauchi            Bauchi
Bayelsa          Yenagoa
Benue            Makurdi
Borno          Maiduguri
Cross River      Calabar
Delta              Asaba
Ebonyi         Abakaliki
dtype: object

In [18]:
colors = pd.Series(["Red", "Blue", "Yellow"])
dfColors = pd.DataFrame(colors, columns=["Primary Colors"], index=[0, 1, 2])
new_index = pd.Index(["casey", "theo", "lily"])
dfColors.set_index(new_index)

Primary Colors
casey            Red
theo            Blue
lily          Yellow

In [26]:
records = pd.DataFrame(np.random.rand(5,5), columns=["Class 1", "Class 2", "Class 3", "Class 4", "Class 5"], index=["Student 1", "Student 2", "Student 3", "Student 4", "Student 5"])
records

Class 1   Class 2   Class 3   Class 4   Class 5
Student 1  0.235643  0.567617  0.570834  0.092068  0.029039
Student 2  0.784041  0.764292  0.221948  0.788479  0.155803
Student 3  0.044404  0.188646  0.178036  0.153866  0.836303
Student 4  0.168211  0.896600  0.111574  0.878133  0.941510
Student 5  0.555204  0.294179  0.430325  0.330676  0.633116

In [44]:
record4 = pd.Series(records.values[3])
record4
new_record = pd.DataFrame(record4, columns=["Student 4"], index=[0, 1, 2, 3, 4])
record4_index = pd.Index(["Class 1", "Class 2", "Class 3", "Class 4", "Class 5"])
print("Record 4 series")
print(record4)
new_record.set_index(record4_index)

Record 4 series
0    0.168211
1    0.896600
2    0.111574
3    0.878133
4    0.941510
dtype: float64


Student 4
Class 1   0.168211
Class 2   0.896600
Class 3   0.111574
Class 4   0.878133
Class 5   0.941510

# Assignment 3
Collate the following informations for every 36 states in Nigeria.
State Name
State Capital
State Population
State Landmass
Create a Pandas Series object of state population and landmass using state name as the key of both.
From the two Series objects, create a DataFrame object and add the state capital as new collumn to the table.
Calculate the population density of each state and use it to generate a new collumn on the DataFrame object.

In [1]:
import pandas as pd
import random

state_names = [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
    'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Gombe', 'Imo',
    'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos',
    'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto',
    'Taraba', 'Yobe', 'Zamfara', 'Federal Capital Territory'
]

state_capitals = [
    'Umuahia', 'Yola', 'Uyo', 'Awka', 'Bauchi', 'Yenagoa', 'Makurdi', 'Maiduguri',
    'Calabar', 'Asaba', 'Abakaliki', 'Benin City', 'Ado-Ekiti', 'Enugu', 'Gombe',
    'Owerri', 'Dutse', 'Kaduna', 'Kano', 'Katsina', 'Birnin Kebbi', 'Lokoja', 'Ilorin',
    'Ikeja', 'Lafia', 'Minna', 'Abeokuta', 'Akure', 'Osogbo', 'Ibadan', 'Jos',
    'Port Harcourt', 'Sokoto', 'Jalingo', 'Damaturu', 'Gusau', 'Abuja'
]


state_population = [random.randint(1000000, 30000000) for _ in range(len(state_names))]
state_landmass = [random.randint(5000, 50000) for _ in range(len(state_names))]


population_series = pd.Series(state_population, index=state_names, name='Population')
landmass_series = pd.Series(state_landmass, index=state_names, name='Landmass')


df = pd.DataFrame({'Population': population_series, 'Landmass': landmass_series})


df['State Capital'] = state_capitals


df['Population Density'] = df['Population'] / df['Landmass']

# Display the resulting DataFrame
print(df)



                           Population  Landmass  State Capital  \
Abia                         22400573     36267        Umuahia   
Adamawa                      27864023     11915           Yola   
Akwa Ibom                    19863270     15459            Uyo   
Anambra                      16373741     45887           Awka   
Bauchi                        3489384     40507         Bauchi   
Bayelsa                      17256008     34701        Yenagoa   
Benue                         6980296     20657        Makurdi   
Borno                        23979637     39514      Maiduguri   
Cross River                  23670558     19416        Calabar   
Delta                        15584832     24505          Asaba   
Ebonyi                       10783740      9544      Abakaliki   
Edo                          28554421     34690     Benin City   
Ekiti                        20648485     24159      Ado-Ekiti   
Enugu                        15662079     44513          Enugu   
Gombe     